"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

triangle = lambda x: (x * (x+1) ) / 2

def divisor_num(x):
    print(x,end=" ")
    i = 2
    number_of_divisor = 1
    powers_of_prime_factors = [0]
    while x != 1:
        if not (x % i):
            x = x // i
            powers_of_prime_factors[-1] += 1
            continue
        if i == 2:
            i += 1
        else:
            i += 2
        if powers_of_prime_factors[-1] != 0:
            powers_of_prime_factors.append(0)

    for i in powers_of_prime_factors:
        number_of_divisor = number_of_divisor * (i + 1)
    print(number_of_divisor)
    return number_of_divisor

x = 1

while True:
    if(divisor_num(triangle(x)) > 500):
        break
    x += 1

print(triangle(x))