"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
from Helper.Timer import Timer
from Helper.Logger import Logger

QUESTION_NUM = 2


def solve():
    timer = Timer()
    timer.set_start_time()
    a = 1
    b = 1
    total = 0
    while True:
        if not a % 2:
            total += a
        b += a
        a, b = b, a
        if a > 4000000:
            break

    return total, timer.get_reset_calculation_time()


if __name__ == "__main__":
    result, time = solve()
    Logger.print_log(QUESTION_NUM, result, time)
