"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
from Helper.Timer import Timer
from Helper.Logger import Logger
from Solutions.Helper import Euler_Helper as EH

QUESTION_NUM = 12


def solve():
    timer = Timer()
    timer.set_start_time()
    x = 1
    while True:
        if EH.divisor_num(EH.triangle(x)) > 500:
            break
        x += 1

    return EH.triangle(x), timer.get_reset_calculation_time()


if __name__ == "__main__":
    result, time = solve()
    Logger.print_log(QUESTION_NUM, result, time)
